exclude_paths:
- ".idea/"
- "chore/"
- "dist/"
- "example/"
- "resources/"
- ".gitignore"
- ".npmignore"
- ".travis.yml"
- "bower.json"
- "CHANGELOG.md"
- "gulpfile.js"
- "karma.config.js"
- "LICENSE"
- "package.json"
- "README.md"
- "tsconfig.json"
- "typings.json"
- "webpack.config.json"



