exclude_paths:
- ".idea/"
- "chore/"
- "dist/"
- "examples/"
- "resources/"
- ".gitignore"
- ".npmignore"
- ".travis.yml"
- "*.json"
- "*.md"
- "gulpfile.js"
- "karma.config.js"
- "webpack.config.js"
- "LICENSE"



