language: node_js
sudo: false
node_js:
- '6.11.0'

cache:
  directories:
     - ./node_modules

install:
  - npm i -g trash
  - npm i

before_script:

script:
  - npm test
  - npm run build
  - npm run update-example
  - cd example/angular4
  - ng build -prod
  - cd ../..